[project]
name = "currency-analyst-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai[tools]>=1.7.2",
    "streamlit>=1.52.2",
]
